name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'backend/api/**'
      - 'backend/worker/**'

jobs:
  build-api:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified + github.event.head_commit.added + github.event.head_commit.removed, 'backend/api/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Start API CodeBuild
      run: |
        aws codebuild start-build --project-name aws-ecs-poc-api-build --source-version ${{ github.sha }}

  build-worker:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified + github.event.head_commit.added + github.event.head_commit.removed, 'backend/worker/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Start Worker CodeBuild
      run: |
        aws codebuild start-build --project-name aws-ecs-poc-worker-build --source-version ${{ github.sha }}